baseURL = "http://www.stroidomodedovo21.ru/"
languageCode = "ru"
defaultContentLanguage = "ru"
title = "Чувашские рабочие"
theme = "freelancer"
publishDir = "docs"
disableKinds = ["taxonomy","taxonomyTerm"]
enableRobotsTXT = true

[params]
    googleAnalytics = "UA-110098479-1"

    custom_css = ["css/domodedovo.css"]
    custom_js  = []

    [params.navigation]
        brand = "Чувашские рабочие"

    [params.header]
        image = "profile.png"
        name = "Чувашские рабочие"
        subtitle = "Разнесем вашу квартиру и сорвем все сроки!"

    [params.portfolio]
        title = "Как мы работаем"

    [params.faces]
        title = "Лица"

    [params.advantages]
        title = "Преимущества"

    [params.about]
        title = "Реквизиты"
        left = "<p><strong>E-mail:</strong> denis12071985@yandex.ru</p><p><strong>Телефон:</strong> +7 925 511-35-65</p>"
        right = "<p><strong>ИП:</strong> Емельянов Денис Николаевич</p><p><strong>ОГРНИП:</strong> 316502700078599</p><p><strong>ИНН:</strong> 211401329188</p><p><strong>Дата регистрации:</strong> 20.12.2016</p><p><strong>Дата прекращения:</strong> 24.10.2017</p>"

    [params.about.button]
        text = "Выписка из ЕГРИП"
        link = "/files/211401329188.pdf"
        icon = ""